version: "2"
run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - goconst
    - gosec
    - misspell
    - unconvert
    - fatcontext
    - perfsprint
    - usetesting
    - recvcheck

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      severity: medium
      confidence: medium
    govet:
      enable:
        - asmdecl
        - assign
        - atomic
        - bools
        - copylocks
        - defers
        - directive
        - errorsas
        - framepointer
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - printf
        - reflectvaluecompare
        - shadow
        - shift
        - sigchanyzer
        - slog
        - sortslice
        - stdmethods
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedwrite
        - unusedresult
    staticcheck:
      checks: ["all"]

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - goconst
      - path: /bigtablepb/
        linters:
          - unused
          - govet
