// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: google/bigtable/v2/bigtable.proto

package bigtablepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bigtable_ReadRows_FullMethodName                              = "/google.bigtable.v2.Bigtable/ReadRows"
	Bigtable_SampleRowKeys_FullMethodName                         = "/google.bigtable.v2.Bigtable/SampleRowKeys"
	Bigtable_MutateRow_FullMethodName                             = "/google.bigtable.v2.Bigtable/MutateRow"
	Bigtable_MutateRows_FullMethodName                            = "/google.bigtable.v2.Bigtable/MutateRows"
	Bigtable_CheckAndMutateRow_FullMethodName                     = "/google.bigtable.v2.Bigtable/CheckAndMutateRow"
	Bigtable_PingAndWarm_FullMethodName                           = "/google.bigtable.v2.Bigtable/PingAndWarm"
	Bigtable_ReadModifyWriteRow_FullMethodName                    = "/google.bigtable.v2.Bigtable/ReadModifyWriteRow"
	Bigtable_GenerateInitialChangeStreamPartitions_FullMethodName = "/google.bigtable.v2.Bigtable/GenerateInitialChangeStreamPartitions"
	Bigtable_ReadChangeStream_FullMethodName                      = "/google.bigtable.v2.Bigtable/ReadChangeStream"
	Bigtable_PrepareQuery_FullMethodName                          = "/google.bigtable.v2.Bigtable/PrepareQuery"
	Bigtable_ExecuteQuery_FullMethodName                          = "/google.bigtable.v2.Bigtable/ExecuteQuery"
	Bigtable_GetClientConfiguration_FullMethodName                = "/google.bigtable.v2.Bigtable/GetClientConfiguration"
	Bigtable_OpenTable_FullMethodName                             = "/google.bigtable.v2.Bigtable/OpenTable"
	Bigtable_OpenAuthorizedView_FullMethodName                    = "/google.bigtable.v2.Bigtable/OpenAuthorizedView"
	Bigtable_OpenMaterializedView_FullMethodName                  = "/google.bigtable.v2.Bigtable/OpenMaterializedView"
)

// BigtableClient is the client API for Bigtable service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for reading from and writing to existing Bigtable tables.
type BigtableClient interface {
	// Streams back the contents of all requested rows in key order, optionally
	// applying the same Reader filter to each. Depending on their size,
	// rows and cells may be broken up across multiple responses, but
	// atomicity of each row will still be preserved. See the
	// ReadRowsResponse documentation for details.
	ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsResponse], error)
	// Returns a sample of row keys in the table. The returned row keys will
	// delimit contiguous sections of the table of approximately equal size,
	// which can be used to break up the data for distributed tasks like
	// mapreduces.
	SampleRowKeys(ctx context.Context, in *SampleRowKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SampleRowKeysResponse], error)
	// Mutates a row atomically. Cells already present in the row are left
	// unchanged unless explicitly changed by `mutation`.
	MutateRow(ctx context.Context, in *MutateRowRequest, opts ...grpc.CallOption) (*MutateRowResponse, error)
	// Mutates multiple rows in a batch. Each individual row is mutated
	// atomically as in MutateRow, but the entire batch is not executed
	// atomically.
	MutateRows(ctx context.Context, in *MutateRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MutateRowsResponse], error)
	// Mutates a row atomically based on the output of a predicate Reader filter.
	CheckAndMutateRow(ctx context.Context, in *CheckAndMutateRowRequest, opts ...grpc.CallOption) (*CheckAndMutateRowResponse, error)
	// Warm up associated instance metadata for this connection.
	// This call is not required but may be useful for connection keep-alive.
	PingAndWarm(ctx context.Context, in *PingAndWarmRequest, opts ...grpc.CallOption) (*PingAndWarmResponse, error)
	// Modifies a row atomically on the server. The method reads the latest
	// existing timestamp and value from the specified columns and writes a new
	// entry based on pre-defined read/modify/write rules. The new value for the
	// timestamp is the greater of the existing timestamp or the current server
	// time. The method returns the new contents of all modified cells.
	ReadModifyWriteRow(ctx context.Context, in *ReadModifyWriteRowRequest, opts ...grpc.CallOption) (*ReadModifyWriteRowResponse, error)
	// Returns the current list of partitions that make up the table's
	// change stream. The union of partitions will cover the entire keyspace.
	// Partitions can be read with `ReadChangeStream`.
	// NOTE: This API is only intended to be used by Apache Beam BigtableIO.
	GenerateInitialChangeStreamPartitions(ctx context.Context, in *GenerateInitialChangeStreamPartitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateInitialChangeStreamPartitionsResponse], error)
	// Reads changes from a table's change stream. Changes will
	// reflect both user-initiated mutations and mutations that are caused by
	// garbage collection.
	// NOTE: This API is only intended to be used by Apache Beam BigtableIO.
	ReadChangeStream(ctx context.Context, in *ReadChangeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadChangeStreamResponse], error)
	// Prepares a GoogleSQL query for execution on a particular Bigtable instance.
	PrepareQuery(ctx context.Context, in *PrepareQueryRequest, opts ...grpc.CallOption) (*PrepareQueryResponse, error)
	// Executes a SQL query against a particular Bigtable instance.
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteQueryResponse], error)
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	GetClientConfiguration(ctx context.Context, in *GetClientConfigurationRequest, opts ...grpc.CallOption) (*ClientConfiguration, error)
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	OpenTable(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error)
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	OpenAuthorizedView(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error)
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	OpenMaterializedView(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error)
}

type bigtableClient struct {
	cc grpc.ClientConnInterface
}

func NewBigtableClient(cc grpc.ClientConnInterface) BigtableClient {
	return &bigtableClient{cc}
}

func (c *bigtableClient) ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[0], Bigtable_ReadRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRowsRequest, ReadRowsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_ReadRowsClient = grpc.ServerStreamingClient[ReadRowsResponse]

func (c *bigtableClient) SampleRowKeys(ctx context.Context, in *SampleRowKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SampleRowKeysResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[1], Bigtable_SampleRowKeys_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SampleRowKeysRequest, SampleRowKeysResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_SampleRowKeysClient = grpc.ServerStreamingClient[SampleRowKeysResponse]

func (c *bigtableClient) MutateRow(ctx context.Context, in *MutateRowRequest, opts ...grpc.CallOption) (*MutateRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateRowResponse)
	err := c.cc.Invoke(ctx, Bigtable_MutateRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigtableClient) MutateRows(ctx context.Context, in *MutateRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MutateRowsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[2], Bigtable_MutateRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MutateRowsRequest, MutateRowsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_MutateRowsClient = grpc.ServerStreamingClient[MutateRowsResponse]

func (c *bigtableClient) CheckAndMutateRow(ctx context.Context, in *CheckAndMutateRowRequest, opts ...grpc.CallOption) (*CheckAndMutateRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAndMutateRowResponse)
	err := c.cc.Invoke(ctx, Bigtable_CheckAndMutateRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigtableClient) PingAndWarm(ctx context.Context, in *PingAndWarmRequest, opts ...grpc.CallOption) (*PingAndWarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingAndWarmResponse)
	err := c.cc.Invoke(ctx, Bigtable_PingAndWarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigtableClient) ReadModifyWriteRow(ctx context.Context, in *ReadModifyWriteRowRequest, opts ...grpc.CallOption) (*ReadModifyWriteRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadModifyWriteRowResponse)
	err := c.cc.Invoke(ctx, Bigtable_ReadModifyWriteRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigtableClient) GenerateInitialChangeStreamPartitions(ctx context.Context, in *GenerateInitialChangeStreamPartitionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateInitialChangeStreamPartitionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[3], Bigtable_GenerateInitialChangeStreamPartitions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateInitialChangeStreamPartitionsRequest, GenerateInitialChangeStreamPartitionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_GenerateInitialChangeStreamPartitionsClient = grpc.ServerStreamingClient[GenerateInitialChangeStreamPartitionsResponse]

func (c *bigtableClient) ReadChangeStream(ctx context.Context, in *ReadChangeStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadChangeStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[4], Bigtable_ReadChangeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadChangeStreamRequest, ReadChangeStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_ReadChangeStreamClient = grpc.ServerStreamingClient[ReadChangeStreamResponse]

func (c *bigtableClient) PrepareQuery(ctx context.Context, in *PrepareQueryRequest, opts ...grpc.CallOption) (*PrepareQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareQueryResponse)
	err := c.cc.Invoke(ctx, Bigtable_PrepareQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigtableClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteQueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[5], Bigtable_ExecuteQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteQueryRequest, ExecuteQueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_ExecuteQueryClient = grpc.ServerStreamingClient[ExecuteQueryResponse]

func (c *bigtableClient) GetClientConfiguration(ctx context.Context, in *GetClientConfigurationRequest, opts ...grpc.CallOption) (*ClientConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientConfiguration)
	err := c.cc.Invoke(ctx, Bigtable_GetClientConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bigtableClient) OpenTable(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[6], Bigtable_OpenTable_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionRequest, SessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_OpenTableClient = grpc.BidiStreamingClient[SessionRequest, SessionResponse]

func (c *bigtableClient) OpenAuthorizedView(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[7], Bigtable_OpenAuthorizedView_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionRequest, SessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_OpenAuthorizedViewClient = grpc.BidiStreamingClient[SessionRequest, SessionResponse]

func (c *bigtableClient) OpenMaterializedView(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionRequest, SessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bigtable_ServiceDesc.Streams[8], Bigtable_OpenMaterializedView_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionRequest, SessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_OpenMaterializedViewClient = grpc.BidiStreamingClient[SessionRequest, SessionResponse]

// BigtableServer is the server API for Bigtable service.
// All implementations must embed UnimplementedBigtableServer
// for forward compatibility.
//
// Service for reading from and writing to existing Bigtable tables.
type BigtableServer interface {
	// Streams back the contents of all requested rows in key order, optionally
	// applying the same Reader filter to each. Depending on their size,
	// rows and cells may be broken up across multiple responses, but
	// atomicity of each row will still be preserved. See the
	// ReadRowsResponse documentation for details.
	ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsResponse]) error
	// Returns a sample of row keys in the table. The returned row keys will
	// delimit contiguous sections of the table of approximately equal size,
	// which can be used to break up the data for distributed tasks like
	// mapreduces.
	SampleRowKeys(*SampleRowKeysRequest, grpc.ServerStreamingServer[SampleRowKeysResponse]) error
	// Mutates a row atomically. Cells already present in the row are left
	// unchanged unless explicitly changed by `mutation`.
	MutateRow(context.Context, *MutateRowRequest) (*MutateRowResponse, error)
	// Mutates multiple rows in a batch. Each individual row is mutated
	// atomically as in MutateRow, but the entire batch is not executed
	// atomically.
	MutateRows(*MutateRowsRequest, grpc.ServerStreamingServer[MutateRowsResponse]) error
	// Mutates a row atomically based on the output of a predicate Reader filter.
	CheckAndMutateRow(context.Context, *CheckAndMutateRowRequest) (*CheckAndMutateRowResponse, error)
	// Warm up associated instance metadata for this connection.
	// This call is not required but may be useful for connection keep-alive.
	PingAndWarm(context.Context, *PingAndWarmRequest) (*PingAndWarmResponse, error)
	// Modifies a row atomically on the server. The method reads the latest
	// existing timestamp and value from the specified columns and writes a new
	// entry based on pre-defined read/modify/write rules. The new value for the
	// timestamp is the greater of the existing timestamp or the current server
	// time. The method returns the new contents of all modified cells.
	ReadModifyWriteRow(context.Context, *ReadModifyWriteRowRequest) (*ReadModifyWriteRowResponse, error)
	// Returns the current list of partitions that make up the table's
	// change stream. The union of partitions will cover the entire keyspace.
	// Partitions can be read with `ReadChangeStream`.
	// NOTE: This API is only intended to be used by Apache Beam BigtableIO.
	GenerateInitialChangeStreamPartitions(*GenerateInitialChangeStreamPartitionsRequest, grpc.ServerStreamingServer[GenerateInitialChangeStreamPartitionsResponse]) error
	// Reads changes from a table's change stream. Changes will
	// reflect both user-initiated mutations and mutations that are caused by
	// garbage collection.
	// NOTE: This API is only intended to be used by Apache Beam BigtableIO.
	ReadChangeStream(*ReadChangeStreamRequest, grpc.ServerStreamingServer[ReadChangeStreamResponse]) error
	// Prepares a GoogleSQL query for execution on a particular Bigtable instance.
	PrepareQuery(context.Context, *PrepareQueryRequest) (*PrepareQueryResponse, error)
	// Executes a SQL query against a particular Bigtable instance.
	ExecuteQuery(*ExecuteQueryRequest, grpc.ServerStreamingServer[ExecuteQueryResponse]) error
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	GetClientConfiguration(context.Context, *GetClientConfigurationRequest) (*ClientConfiguration, error)
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	OpenTable(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	OpenAuthorizedView(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error
	// This RPC is only intended to be used by the official Cloud Bigtable client
	// libraries to implement the Bigtable Session based protocol. It is subject
	// to change without notice.
	OpenMaterializedView(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error
	mustEmbedUnimplementedBigtableServer()
}

// UnimplementedBigtableServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBigtableServer struct{}

func (UnimplementedBigtableServer) ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadRows not implemented")
}
func (UnimplementedBigtableServer) SampleRowKeys(*SampleRowKeysRequest, grpc.ServerStreamingServer[SampleRowKeysResponse]) error {
	return status.Error(codes.Unimplemented, "method SampleRowKeys not implemented")
}
func (UnimplementedBigtableServer) MutateRow(context.Context, *MutateRowRequest) (*MutateRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MutateRow not implemented")
}
func (UnimplementedBigtableServer) MutateRows(*MutateRowsRequest, grpc.ServerStreamingServer[MutateRowsResponse]) error {
	return status.Error(codes.Unimplemented, "method MutateRows not implemented")
}
func (UnimplementedBigtableServer) CheckAndMutateRow(context.Context, *CheckAndMutateRowRequest) (*CheckAndMutateRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAndMutateRow not implemented")
}
func (UnimplementedBigtableServer) PingAndWarm(context.Context, *PingAndWarmRequest) (*PingAndWarmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PingAndWarm not implemented")
}
func (UnimplementedBigtableServer) ReadModifyWriteRow(context.Context, *ReadModifyWriteRowRequest) (*ReadModifyWriteRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadModifyWriteRow not implemented")
}
func (UnimplementedBigtableServer) GenerateInitialChangeStreamPartitions(*GenerateInitialChangeStreamPartitionsRequest, grpc.ServerStreamingServer[GenerateInitialChangeStreamPartitionsResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateInitialChangeStreamPartitions not implemented")
}
func (UnimplementedBigtableServer) ReadChangeStream(*ReadChangeStreamRequest, grpc.ServerStreamingServer[ReadChangeStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadChangeStream not implemented")
}
func (UnimplementedBigtableServer) PrepareQuery(context.Context, *PrepareQueryRequest) (*PrepareQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareQuery not implemented")
}
func (UnimplementedBigtableServer) ExecuteQuery(*ExecuteQueryRequest, grpc.ServerStreamingServer[ExecuteQueryResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedBigtableServer) GetClientConfiguration(context.Context, *GetClientConfigurationRequest) (*ClientConfiguration, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientConfiguration not implemented")
}
func (UnimplementedBigtableServer) OpenTable(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenTable not implemented")
}
func (UnimplementedBigtableServer) OpenAuthorizedView(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenAuthorizedView not implemented")
}
func (UnimplementedBigtableServer) OpenMaterializedView(grpc.BidiStreamingServer[SessionRequest, SessionResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenMaterializedView not implemented")
}
func (UnimplementedBigtableServer) mustEmbedUnimplementedBigtableServer() {}
func (UnimplementedBigtableServer) testEmbeddedByValue()                  {}

// UnsafeBigtableServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BigtableServer will
// result in compilation errors.
type UnsafeBigtableServer interface {
	mustEmbedUnimplementedBigtableServer()
}

func RegisterBigtableServer(s grpc.ServiceRegistrar, srv BigtableServer) {
	// If the following call panics, it indicates UnimplementedBigtableServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bigtable_ServiceDesc, srv)
}

func _Bigtable_ReadRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BigtableServer).ReadRows(m, &grpc.GenericServerStream[ReadRowsRequest, ReadRowsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_ReadRowsServer = grpc.ServerStreamingServer[ReadRowsResponse]

func _Bigtable_SampleRowKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SampleRowKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BigtableServer).SampleRowKeys(m, &grpc.GenericServerStream[SampleRowKeysRequest, SampleRowKeysResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_SampleRowKeysServer = grpc.ServerStreamingServer[SampleRowKeysResponse]

func _Bigtable_MutateRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigtableServer).MutateRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bigtable_MutateRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigtableServer).MutateRow(ctx, req.(*MutateRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bigtable_MutateRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MutateRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BigtableServer).MutateRows(m, &grpc.GenericServerStream[MutateRowsRequest, MutateRowsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_MutateRowsServer = grpc.ServerStreamingServer[MutateRowsResponse]

func _Bigtable_CheckAndMutateRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAndMutateRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigtableServer).CheckAndMutateRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bigtable_CheckAndMutateRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigtableServer).CheckAndMutateRow(ctx, req.(*CheckAndMutateRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bigtable_PingAndWarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingAndWarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigtableServer).PingAndWarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bigtable_PingAndWarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigtableServer).PingAndWarm(ctx, req.(*PingAndWarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bigtable_ReadModifyWriteRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadModifyWriteRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigtableServer).ReadModifyWriteRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bigtable_ReadModifyWriteRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigtableServer).ReadModifyWriteRow(ctx, req.(*ReadModifyWriteRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bigtable_GenerateInitialChangeStreamPartitions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateInitialChangeStreamPartitionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BigtableServer).GenerateInitialChangeStreamPartitions(m, &grpc.GenericServerStream[GenerateInitialChangeStreamPartitionsRequest, GenerateInitialChangeStreamPartitionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_GenerateInitialChangeStreamPartitionsServer = grpc.ServerStreamingServer[GenerateInitialChangeStreamPartitionsResponse]

func _Bigtable_ReadChangeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadChangeStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BigtableServer).ReadChangeStream(m, &grpc.GenericServerStream[ReadChangeStreamRequest, ReadChangeStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_ReadChangeStreamServer = grpc.ServerStreamingServer[ReadChangeStreamResponse]

func _Bigtable_PrepareQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigtableServer).PrepareQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bigtable_PrepareQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigtableServer).PrepareQuery(ctx, req.(*PrepareQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bigtable_ExecuteQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BigtableServer).ExecuteQuery(m, &grpc.GenericServerStream[ExecuteQueryRequest, ExecuteQueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_ExecuteQueryServer = grpc.ServerStreamingServer[ExecuteQueryResponse]

func _Bigtable_GetClientConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigtableServer).GetClientConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bigtable_GetClientConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigtableServer).GetClientConfiguration(ctx, req.(*GetClientConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bigtable_OpenTable_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BigtableServer).OpenTable(&grpc.GenericServerStream[SessionRequest, SessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_OpenTableServer = grpc.BidiStreamingServer[SessionRequest, SessionResponse]

func _Bigtable_OpenAuthorizedView_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BigtableServer).OpenAuthorizedView(&grpc.GenericServerStream[SessionRequest, SessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_OpenAuthorizedViewServer = grpc.BidiStreamingServer[SessionRequest, SessionResponse]

func _Bigtable_OpenMaterializedView_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BigtableServer).OpenMaterializedView(&grpc.GenericServerStream[SessionRequest, SessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bigtable_OpenMaterializedViewServer = grpc.BidiStreamingServer[SessionRequest, SessionResponse]

// Bigtable_ServiceDesc is the grpc.ServiceDesc for Bigtable service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bigtable_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.bigtable.v2.Bigtable",
	HandlerType: (*BigtableServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MutateRow",
			Handler:    _Bigtable_MutateRow_Handler,
		},
		{
			MethodName: "CheckAndMutateRow",
			Handler:    _Bigtable_CheckAndMutateRow_Handler,
		},
		{
			MethodName: "PingAndWarm",
			Handler:    _Bigtable_PingAndWarm_Handler,
		},
		{
			MethodName: "ReadModifyWriteRow",
			Handler:    _Bigtable_ReadModifyWriteRow_Handler,
		},
		{
			MethodName: "PrepareQuery",
			Handler:    _Bigtable_PrepareQuery_Handler,
		},
		{
			MethodName: "GetClientConfiguration",
			Handler:    _Bigtable_GetClientConfiguration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadRows",
			Handler:       _Bigtable_ReadRows_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SampleRowKeys",
			Handler:       _Bigtable_SampleRowKeys_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MutateRows",
			Handler:       _Bigtable_MutateRows_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateInitialChangeStreamPartitions",
			Handler:       _Bigtable_GenerateInitialChangeStreamPartitions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadChangeStream",
			Handler:       _Bigtable_ReadChangeStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteQuery",
			Handler:       _Bigtable_ExecuteQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenTable",
			Handler:       _Bigtable_OpenTable_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenAuthorizedView",
			Handler:       _Bigtable_OpenAuthorizedView_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenMaterializedView",
			Handler:       _Bigtable_OpenMaterializedView_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "google/bigtable/v2/bigtable.proto",
}
